import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Header from './components/Header';
import Head from 'next/head'; 
import Image from "next/image"
import { Analytics } from "@vercel/analytics/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Akhshad Gorle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark"> 
  
     <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" sizes="32x32" href="/AG.png" />
        {/* <link rel="icon" href="/favicon.svg" type="image/svg+xml" /> */}
      </Head>
       <body className={inter.className}>
        <Header />
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
